name: crash-point-database

services:
  postgres:
    image: postgres:17
    volumes:
      - crash-point-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

volumes:
  crash-point-postgres-data: